import and preprocessing the given datasets

In [2]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [3]:
data=pd.read_csv('/content/drive/MyDrive/ml mini projects/movies.csv')

In [4]:
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [5]:
data.shape

(4803, 24)

In [6]:
selectedFeatures = ['genres','keywords','overview','tagline','cast','director']
print(selectedFeatures)

['genres', 'keywords', 'overview', 'tagline', 'cast', 'director']


In [7]:
for feature in selectedFeatures:
  data[feature]=data[feature].fillna("")

In [8]:
comFeatures = data['genres']+data['keywords']+data['overview']+data['tagline']+data['cast']+data['director']
print(comFeatures)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    When ambitious New York attorney Sam is sent t...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [9]:
vector = TfidfVectorizer()
featureVector = vector.fit_transform(comFeatures)
print(featureVector)

  (0, 5503)	0.12851987506039134
  (0, 31084)	0.20972605417816464
  (0, 24304)	0.11729818028068979
  (0, 21473)	0.16694643157272987
  (0, 34830)	0.12048634402730937
  (0, 39854)	0.14758485475124714
  (0, 33482)	0.1547500805684794
  (0, 31984)	0.16503535093640637
  (0, 41168)	0.1442864101527829
  (0, 40687)	0.17981538373009082
  (0, 32030)	0.11257493992023024
  (0, 26552)	0.030363106625038827
  (0, 40649)	0.06976133045926865
  (0, 12442)	0.13880514542831832
  (0, 6723)	0.15863034384575367
  (0, 1382)	0.12048634402730937
  (0, 1656)	0.052019533237400384
  (0, 29134)	0.16007780288612455
  (0, 1693)	0.030441494970065937
  (0, 26831)	0.1547500805684794
  (0, 14579)	0.13820066347113272
  (0, 3839)	0.095124443735071
  (0, 37269)	0.14006205467854133
  (0, 3482)	0.09341830651998566
  (0, 5303)	0.059028576219542425
  :	:
  (4802, 37757)	0.07843764997361562
  (4802, 36424)	0.05974550873970907
  (4802, 26349)	0.06108180610873494
  (4802, 16664)	0.07795031657907454
  (4802, 39941)	0.0770180406882288

In [10]:
similarity = cosine_similarity(featureVector)
print(similarity)
similarity.shape

[[1.         0.04651794 0.02122374 ... 0.02538798 0.03210693 0.00612798]
 [0.04651794 1.         0.03945313 ... 0.04955816 0.03187544 0.01488931]
 [0.02122374 0.03945313 1.         ... 0.02570582 0.01200746 0.01342171]
 ...
 [0.02538798 0.04955816 0.02570582 ... 1.         0.03869624 0.02633318]
 [0.03210693 0.03187544 0.01200746 ... 0.03869624 1.         0.03292613]
 [0.00612798 0.01488931 0.01342171 ... 0.02633318 0.03292613 1.        ]]


(4803, 4803)

Now we are moving into recommendation algorithm

In [13]:
movieName = input('Enter your favourite movie name: ')

Enter your favourite movie name: interstellar


In [14]:
listTitles = data['title'].tolist()
print(listTitles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [15]:
findCloseMatch = difflib.get_close_matches(movieName,listTitles)
print(findCloseMatch)

['Interstellar', 'Cinderella', 'Cinderella Man']


In [16]:
closeMatch=findCloseMatch[0]
print(closeMatch)

Interstellar


In [17]:
movieIndex = data[data.title == closeMatch]['index'].values[0]
print(movieIndex)

95


In [18]:
similarityScore = list(enumerate(similarity[movieIndex]))
print(similarityScore)

[(0, 0.06074918856217834), (1, 0.0552502593980827), (2, 0.026841083113409405), (3, 0.09009276071020582), (4, 0.07355832393548661), (5, 0.015508058046366279), (6, 0.027984345797336017), (7, 0.05483473381167378), (8, 0.024520671409710516), (9, 0.04683005093779141), (10, 0.07122877715343598), (11, 0.04501944703697502), (12, 0.012154482331626006), (13, 0.03101705827447923), (14, 0.13480552962430575), (15, 0.06329283255143764), (16, 0.03624996162533487), (17, 0.06189703502092505), (18, 0.05948954446774181), (19, 0.06564843016329296), (20, 0.05919279000607103), (21, 0.020938044491108074), (22, 0.018887837418873128), (23, 0.02818291338778697), (24, 0.043241242245169335), (25, 0.04831650912524242), (26, 0.036781495292490016), (27, 0.07932632495479104), (28, 0.019715106494057395), (29, 0.042668489881078075), (30, 0.027727535935973532), (31, 0.035332215167714516), (32, 0.07570495029929358), (33, 0.02492894164650195), (34, 0.026309300651628318), (35, 0.015026437948692756), (36, 0.0494065802426159

In [19]:
SortedSimilarMovies=sorted(similarityScore, key = lambda x:x[1],reverse=True)
print(SortedSimilarMovies)

[(95, 1.0), (634, 0.16968692322309123), (14, 0.13480552962430575), (220, 0.12725730457260956), (123, 0.12380310037646589), (1446, 0.12136653463308864), (365, 0.11000454530245504), (2752, 0.10538815999728286), (4110, 0.10150552309749758), (300, 0.10144608641265952), (1787, 0.10102122655676599), (643, 0.09895776626149018), (116, 0.09709837066970539), (1393, 0.09662904554925834), (162, 0.09645895964319208), (125, 0.09641991527340245), (342, 0.09633365201770616), (1551, 0.09608715470757051), (1611, 0.09501701754634499), (1531, 0.09463847321758373), (2705, 0.09424898693512875), (1759, 0.09373955601215801), (3439, 0.09317920397094875), (1645, 0.09267869277180597), (539, 0.0917147024130503), (2240, 0.09160816016386326), (3688, 0.09119653761408471), (3579, 0.09092767127541668), (3093, 0.09062721315662639), (3, 0.09009276071020582), (3165, 0.08925996505588445), (2696, 0.08910963146443071), (4176, 0.0887558000988358), (150, 0.08812384395966034), (870, 0.08768474079172914), (1352, 0.0876187211400

In [20]:
print("Movie suggest for you : \n")
i=1
for movie in SortedSimilarMovies:
  index = movie[0]
  titlefromIndex = data[data.index==index]["title"].values[0]
  if(i<=30):
    print(i,".",titlefromIndex)
    i+=1

Movie suggest for you : 

1 . Interstellar
2 . The Matrix
3 . Man of Steel
4 . Prometheus
5 . The Matrix Revolutions
6 . The Tree of Life
7 . Contact
8 . Ex Machina
9 . Inside Deep Throat
10 . Starship Troopers
11 . A Bridge Too Far
12 . Space Cowboys
13 . I Am Legend
14 . Must Love Dogs
15 . Stealth
16 . The Matrix Reloaded
17 . Men in Black
18 . The Princess Diaries
19 . Mortal Kombat: Annihilation
20 . Moonraker
21 . Soul Survivors
22 . The Right Stuff
23 . The Terminator
24 . The Cave
25 . Titan A.E.
26 . A Most Violent Year
27 . Dear Frankie
28 . The Man from Snowy River
29 . Owning Mahowny
30 . The Dark Knight Rises


Movie Recommendation System

In [27]:
movieName = input('Enter your favourite movie name: ')

listTitles = data['title'].tolist()

findCloseMatch = difflib.get_close_matches(movieName,listTitles)

closeMatch=findCloseMatch[0]

movieIndex = data[data.title == closeMatch]['index'].values[0]

similarityScore = list(enumerate(similarity[movieIndex]))

SortedSimilarMovies=sorted(similarityScore, key = lambda x:x[1],reverse=True)

print("Movie suggest for you : \n")
i=1
for movie in SortedSimilarMovies:
  index = movie[0]
  titlefromIndex = data[data.index==index]["title"].values[0]
  if(i<=30):
    print(i,".",titlefromIndex)
    i+=1

Enter your favourite movie name: the pirates of the caribbean
Movie suggest for you : 

1 . Pirates of the Caribbean: At World's End
2 . Pirates of the Caribbean: Dead Man's Chest
3 . Pirates of the Caribbean: The Curse of the Black Pearl
4 . Anna and the King
5 . Exorcist: The Beginning
6 . Thor
7 . Cast Away
8 . The Prophecy
9 . The Glass House
10 . Angels & Demons
11 . The Lord of the Rings: The Return of the King
12 . The Lord of the Rings: The Fellowship of the Ring
13 . Star Trek Into Darkness
14 . Arn: The Knight Templar
15 . The Prince of Egypt
16 . The Brothers Bloom
17 . Broken Vessels
18 . The Other Side of Heaven
19 . Battleship
20 . Guiana 1838
21 . Mamma Mia!
22 . Men in Black II
23 . The Three Musketeers
24 . Dragonball Evolution
25 . Evil Dead
26 . 2012
27 . Big Fish
28 . Roadside Romeo
29 . How to Train Your Dragon 2
30 . Hercules
